[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#E84300"
backgroundColor = "#FAFAF5"
secondaryBackgroundColor = "#F0EBE3"
textColor = "#1C1816"
